baseURL = 'http://rossabaker.com/'
languageCode = 'en-us'
title = 'Ross A. Baker'

assetDir = 'src/hugo/assets'
layoutDir = 'src/hugo/layouts'
staticDir = 'src/hugo/static'
contentDir = '.hugo-out/content'

[markup.goldmark.renderer]
  unsafe = true
